// <auto-generated />
using System;
using BTCPayServer.Plugins.ZCash.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.ZCash.Data.Migrations
{
    partial class AddRecoveryCursors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.ZCash")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.ZCash.Data.Models.ZcashRecoveryCursor", b =>
                {
                    b.Property<string>("CryptoCode").HasColumnType("text");
                    b.Property<long>("AccountIndex").HasColumnType("bigint");
                    b.Property<long>("Height").HasColumnType("bigint");
                    b.HasKey("CryptoCode", "AccountIndex");
                    b.ToTable("RecoveryCursors", "BTCPayServer.Plugins.ZCash");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.ZCash.Data.Models.ZcashReceiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountIndex")
                        .HasColumnType("integer");

                    b.Property<int>("AddressIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<string>("OrchardAddress")
                        .HasColumnType("text");

                    b.Property<string>("SaplingAddress")
                        .HasColumnType("text");

                    b.Property<string>("TransparentAddress")
                        .HasColumnType("text");

                    b.Property<string>("UnifiedAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OrchardAddress");

                    b.HasIndex("SaplingAddress");

                    b.HasIndex("TransparentAddress");

                    b.HasIndex("UnifiedAddress")
                        .IsUnique();

                    b.ToTable("Receivers", "BTCPayServer.Plugins.ZCash");
                });
#pragma warning restore 612, 618
        }
    }
}
